server:
  port: ${PORT0:88}

xop:
  wechat:
    mp:
      appId: wx37abeff2db731a8e
      secret: 35e0f127fca4b02e96a7cd12aac2150c
      token: token123abc
      aesKey: TrZYdBby86AP1C7juMakFi5uW1Nn6x7GPDC7NRkPPhn
    auth:
      host: ${HOST_REMOTE:http://127.0.0.1:9819}
      redirectPrefix: ${xop.wechat.auth.host}/redirect
      authorizeUrl: https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=snsapi_userinfo&state=123456#wechat_redirect
      homeUrl: ${xop.wechat.auth.host}/web/p/index.html
      errorUrl: ${xop.wechat.auth.host}/web/error.html
      authPattern: ["/web/p/**"]
     